Design layout HTML
st-linhdoan/FE-Internship-2021_Linh-Doan-T-B_FE-Exercise pull request #4
Opened 2021-04-08 02:29 UTC by st-linhdoan

__Description__
  - Dựng layout bằng HTML theo design có sẵn  
  - Đặt tên class cho các thẻ
  
__Reference__
 #3

2021-04-08 17:07 UTC, st-dieple commented on excercise_html/home.html
> +            <img class="header-logo-img" src="image/img/Logo.png" alt="Shopka"/>
Không cần `/` cuối thẻ img. Kiểm tra các thẻ img khác

2021-04-08 17:07 UTC, st-dieple commented on excercise_html/home.html
> +      <div class="container">
`div` này đang bị dư, vì đã có `main` bọc ngoài cùng.
Bỏ `div` và dùng class `container` cho `main`

2021-04-08 17:07 UTC, st-dieple commented on excercise_html/home.html
> +          <div class="container">
không dùng `container` bên trong `container` vì
`container` là class dùng quy định chung cho phần chứa nội dung của section hoặc cả trang, và chỉ dùng một lần.
Trường hợp này đã có `<main class="container"></main>` bọc ngoài tất cả nội dung
-> ko cần thẻ `div` này

2021-04-08 17:07 UTC, st-dieple commented on excercise_html/home.html
> +            <img class="banner-img" src="image/img/image 1.png" />
tên image nên là `image-1`. không nên có dấu cách trong tên image
thêm alt text nữa nha

2021-04-08 17:07 UTC, st-dieple commented on excercise_html/home.html
> +                  <img src="image/img/Image(1).png" />
Không cần viết hoa tên image đâu nha, cả dấu `()` nữa
đơn giản `image-1.png` là được rồi

2021-04-08 17:07 UTC, st-dieple commented on excercise_html/home.html
> +              <select name="Useless First">
thuộc tính `name` nên được đặt như cách đặt tên một biến (liền chuỗi, không có dấu cách)
vì có thể sử dụng trong javascript.
Suggest: `<select name="uselessFirst">`
Sửa và áp dụng tương tự cho các thẻ khác nếu có (input, button...)

2021-04-08 17:07 UTC, st-dieple commented on excercise_html/home.html
> +                    <h4 class="product-list-item-caption-name">
Tên class quá dài. Cố gắng đặt class với tối đa 3 phần nối (aa-bb-cc)
Có thể tham khảo:
`product-list-item` -> `product-item`
`product-list-item-caption` -> `product-info`
`product-list-item-caption-name` -> `product-name` (là tên của product chứ không phải tên của `product-list-item-caption` 😉)

2021-04-08 17:07 UTC, st-dieple commented on excercise_html/home.html
> +        <nav>
ko dùng <nav> ở đây. Dư và không đúng ý nghĩa.
<nav> sẽ dùng cho phần menu, chứa các thẻ a để điều hướng đến các trang khác của web.

2021-04-09 06:45 UTC, st-dungnguyen commented on excercise_html/home.html
> +
dư dòng cuối file. Chỉ 1 dòng là đủ

2021-04-09 07:54 UTC, st-dieple commented
LGTM!

2021-04-09 08:59 UTC, st-dungnguyen requested changes

2021-04-09 08:59 UTC, st-dungnguyen commented on excercise_html/home.html
> +                    >$12.48 <span class="badge-sale">50% OFF</span></span
rớt dòng

2021-04-09 08:59 UTC, st-dungnguyen commented on excercise_html/home.html
> +                <img src="image/img/image-5.png" class="Product 5" />
`atl="Product 5"`

2021-04-09 08:59 UTC, st-dungnguyen commented on excercise_html/home.html
> +      <div class="container">
Footer khác design với header và main nên không dùng container chỗ này

2021-04-09 08:59 UTC, st-dungnguyen commented on excercise_html/home.html
> +                    >$1.25 <span class="badge-deal"> Cool deal</span></span
như trên

2021-04-09 08:59 UTC, st-dungnguyen commented on excercise_html/home.html
> +            <select name="uselessFirst" class="select select-use">
name và value sử dung kebab-case ví dụ `useless-first`.
Thường thì đặt 1 chữ cho dễ.

2021-04-12 01:25 UTC, st-dungnguyen requested changes

2021-04-12 01:25 UTC, st-dungnguyen commented on excercise_html/home.html
> +              <span class="badge badge-cart" id="lblCartCount ">1</span>
`id="lblCartCount "` dư white space và sử dụng kebab-case

2021-04-12 01:25 UTC, st-dungnguyen commented on excercise_html/home.html
> +            />
Thẻ `<img>` không cần `/` phía sau, remove cho tất cả các thẻ `img`

2021-04-13 02:54 UTC, merged